version: '3.8'

services:
  backend:
    build:
      context: ./server
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=production

  frontend:
    build:
      context: ./client
    ports:
      - "3000:80"
    depends_on:
      - backend